services:
  mqtt-ui:
    image: ghcr.io/gaetancollaud/mqtt-ui
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native-micro
    ports:
      - 8080:8080
    env_file:
      - .env
