mp:
  messaging:
    incoming:
      mqtt-raw-in:
        concurrency: 1
        buffer-size: 10000
        max-message-size: 1000000
        connector: smallrye-mqtt
        topic: "#"
        host: ${mqttui.mqtt.host}
        port: ${mqttui.mqtt.port}
        username: ${mqttui.mqtt.username}
        password: ${mqttui.mqtt.password}
#    outgoing:
#      mqtt-raw-out:
#        connector: smallrye-mqtt
#        host: ${mqttui.mqtt.host}
#        port: ${mqttui.mqtt.port}
#        username: ${mqttui.mqtt.username}
#        password: ${mqttui.mqtt.password}

quarkus:
  http:
    enable-compression: true
  quinoa:
    build-dir: dist/webui/browser
    dev-server-port: 4200
    enable-spa-routing: true
  console:
    color: true
  native:
    additional-build-args:
      - -march=compatibility
  log:
    category:
      "io.smallrye.reactive.messaging.mqtt":
        level: WARN


mqttui:
  mqtt:
    host: localhost
    port: 1883
    username:
    password:


"%dev":
  quarkus:
    quinoa:
      ~: false
