name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx4g
      DOCKER_BUILDKIT: 1

    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Prepare Image Build
        id: prep_image
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.actor }}/mqtt-ui
          TAG="${DOCKER_IMAGE}:latest"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Maven version
        run: mvn -v
      - name: Build with Maven
        run: mvn --batch-mode clean package -DskipTests
      - name: Build native
        run: mvn --batch-mode package -DskipTests -Pnative

      - name: Log in to the GitHub Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          push: true
          tags: ${{ steps.prep_image.outputs.tags }}

